services:
    app.search_adapter.symfony_finder:
        class:   Alexkomaralex\FileSearchBundle\Adapter\SymfonyFinder

    app.search_adapter.php_iterator:
        class:   Alexkomaralex\FileSearchBundle\Adapter\PhpIterator

    app.command.find_command:
        class: Alexkomaralex\FileSearchBundle\Command\FindCommand
        arguments: ["@app.search_adapter.symfony_finder"]
        tags:
            -  { name: console.command }

#    app.command.find_command:
#        class: Alexkomaralex\FileSearchBundle\Command\FindCommand
#        arguments: ["@app.search_adapter.php_iterator"]
#        tags:
#            -  { name: console.command }